INSERT INTO STATUSNAME (STATUS) VALUES ('PENDING');
INSERT INTO STATUSNAME (STATUS) VALUES ('CLAIMED');
INSERT INTO STATUSNAME (STATUS) VALUES ('UNCLAIMED');
INSERT INTO STATUSNAME (STATUS) VALUES ('CANCELLED');
INSERT INTO STATUSNAME (STATUS) VALUES ('INAPPROPRIATE');
INSERT INTO STATUSNAME (STATUS) VALUES ('COMPLETED');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Engineering in Aeronautical Engineering');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Engineering in Aircraft Maintenance and Airworthiness Engineering');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Arts in Applied Languages');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Architecture');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Arts');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Biological and Chemical Sciences');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Business Studies');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Engineering in Chemical & Biochemical Engineering');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Computing Technologies');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Construction Management and Engineering');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Creative Media and Interaction Design');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Arts in Criminal Justice');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Engineering in Electronic and Computer Engineering');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Engineering (Common Entry)');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Equine Science');
INSERT INTO MAJOR (MAJOR) VALUES ('Certificate/Diploma in Equine Science');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Arts in European Studies');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Financial Mathematics');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Food Science and Health');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Arts in International Business');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Arts in Journalism and New Media');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Laws (Law Plus)');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Arts in Law and Accounting');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Mathematics');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Medicine, Bachelor of Surgery');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Midwifery');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Nursing (General)');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Nursing (Mental Health)');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Nursing Studies (for international students)');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Paramedic Studies');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Arts in Performing Arts');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Physical Education with concurrent Teacher Education');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Physics');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Physiotherapy');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Product Design and Technology');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Psychology');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Arts in Psychology and Sociology');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science with concurrent Teacher Education (Biology and Chemistry or Physics or Agricultural Science)');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science with concurrent Teacher Education (Physical Sciences with Chemistry and Physics)');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Sport & Exercise Sciences');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Technology (Education) in Materials & Architectural Technology');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Technology (Education) in Materials & Engineering Technology');
INSERT INTO MAJOR (MAJOR) VALUES ('Bachelor of Science in Technology Management');
